version: '3'
services:
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - '8084:8080'
    depends_on:
      - 'postgres'
    env_file:
      - .env
    restart: always
  postgres:
    image: postgres:latest
    ports:
      - '15432:5432'
    env_file:
      - .env
    restart: always
    volumes: 
      - ./00-postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
      - ./postgres-data:/var/lib/postgresql/data
  chatbot:
    image: chatbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501